# Generated by Django 2.1 on 2018-08-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180827_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
